// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/bstevary/hexagonal/database/db (interfaces: Database)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	db "github.com/bstevary/hexagonal/database/db"
	model "github.com/bstevary/hexagonal/database/model"
	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockDatabase is a mock of Database interface.
type MockDatabase struct {
	ctrl     *gomock.Controller
	recorder *MockDatabaseMockRecorder
}

// MockDatabaseMockRecorder is the mock recorder for MockDatabase.
type MockDatabaseMockRecorder struct {
	mock *MockDatabase
}

// NewMockDatabase creates a new mock instance.
func NewMockDatabase(ctrl *gomock.Controller) *MockDatabase {
	mock := &MockDatabase{ctrl: ctrl}
	mock.recorder = &MockDatabaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDatabase) EXPECT() *MockDatabaseMockRecorder {
	return m.recorder
}

// ActivateUserAccountTx mocks base method.
func (m *MockDatabase) ActivateUserAccountTx(arg0 context.Context, arg1 db.ActivateUserAccountTxParams) (db.ActivateUserAccountTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivateUserAccountTx", arg0, arg1)
	ret0, _ := ret[0].(db.ActivateUserAccountTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ActivateUserAccountTx indicates an expected call of ActivateUserAccountTx.
func (mr *MockDatabaseMockRecorder) ActivateUserAccountTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivateUserAccountTx", reflect.TypeOf((*MockDatabase)(nil).ActivateUserAccountTx), arg0, arg1)
}

// AlterUserAccountStatus mocks base method.
func (m *MockDatabase) AlterUserAccountStatus(arg0 context.Context, arg1 model.AlterUserAccountStatusParams) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AlterUserAccountStatus", arg0, arg1)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AlterUserAccountStatus indicates an expected call of AlterUserAccountStatus.
func (mr *MockDatabaseMockRecorder) AlterUserAccountStatus(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AlterUserAccountStatus", reflect.TypeOf((*MockDatabase)(nil).AlterUserAccountStatus), arg0, arg1)
}

// CountUsers mocks base method.
func (m *MockDatabase) CountUsers(arg0 context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountUsers", arg0)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountUsers indicates an expected call of CountUsers.
func (mr *MockDatabaseMockRecorder) CountUsers(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountUsers", reflect.TypeOf((*MockDatabase)(nil).CountUsers), arg0)
}

// CreateActivateAccountEmail mocks base method.
func (m *MockDatabase) CreateActivateAccountEmail(arg0 context.Context, arg1 model.CreateActivateAccountEmailParams) (model.VarifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateActivateAccountEmail", arg0, arg1)
	ret0, _ := ret[0].(model.VarifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateActivateAccountEmail indicates an expected call of CreateActivateAccountEmail.
func (mr *MockDatabaseMockRecorder) CreateActivateAccountEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateActivateAccountEmail", reflect.TypeOf((*MockDatabase)(nil).CreateActivateAccountEmail), arg0, arg1)
}

// CreateSession mocks base method.
func (m *MockDatabase) CreateSession(arg0 context.Context, arg1 model.CreateSessionParams) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSession", arg0, arg1)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSession indicates an expected call of CreateSession.
func (mr *MockDatabaseMockRecorder) CreateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSession", reflect.TypeOf((*MockDatabase)(nil).CreateSession), arg0, arg1)
}

// CreateUser mocks base method.
func (m *MockDatabase) CreateUser(arg0 context.Context, arg1 model.CreateUserParams) (model.CreateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", arg0, arg1)
	ret0, _ := ret[0].(model.CreateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockDatabaseMockRecorder) CreateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockDatabase)(nil).CreateUser), arg0, arg1)
}

// CreateUserTx mocks base method.
func (m *MockDatabase) CreateUserTx(arg0 context.Context, arg1 db.CreateUserTxParams) (db.CreateUserTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserTx", arg0, arg1)
	ret0, _ := ret[0].(db.CreateUserTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserTx indicates an expected call of CreateUserTx.
func (mr *MockDatabaseMockRecorder) CreateUserTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserTx", reflect.TypeOf((*MockDatabase)(nil).CreateUserTx), arg0, arg1)
}

// DeleteSession mocks base method.
func (m *MockDatabase) DeleteSession(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSession indicates an expected call of DeleteSession.
func (mr *MockDatabaseMockRecorder) DeleteSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSession", reflect.TypeOf((*MockDatabase)(nil).DeleteSession), arg0, arg1)
}

// DeleteUser mocks base method.
func (m *MockDatabase) DeleteUser(arg0 context.Context, arg1 string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteUser", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockDatabaseMockRecorder) DeleteUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockDatabase)(nil).DeleteUser), arg0, arg1)
}

// GetSession mocks base method.
func (m *MockDatabase) GetSession(arg0 context.Context, arg1 uuid.UUID) (model.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession", arg0, arg1)
	ret0, _ := ret[0].(model.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSession indicates an expected call of GetSession.
func (mr *MockDatabaseMockRecorder) GetSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockDatabase)(nil).GetSession), arg0, arg1)
}

// ListUsers mocks base method.
func (m *MockDatabase) ListUsers(arg0 context.Context, arg1 model.ListUsersParams) ([]model.ListUsersRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListUsers", arg0, arg1)
	ret0, _ := ret[0].([]model.ListUsersRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockDatabaseMockRecorder) ListUsers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockDatabase)(nil).ListUsers), arg0, arg1)
}

// SelectUserByEmail mocks base method.
func (m *MockDatabase) SelectUserByEmail(arg0 context.Context, arg1 string) (model.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectUserByEmail", arg0, arg1)
	ret0, _ := ret[0].(model.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectUserByEmail indicates an expected call of SelectUserByEmail.
func (mr *MockDatabaseMockRecorder) SelectUserByEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectUserByEmail", reflect.TypeOf((*MockDatabase)(nil).SelectUserByEmail), arg0, arg1)
}

// UpdateActivateAccountEmail mocks base method.
func (m *MockDatabase) UpdateActivateAccountEmail(arg0 context.Context, arg1 string) (model.VarifyEmail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateActivateAccountEmail", arg0, arg1)
	ret0, _ := ret[0].(model.VarifyEmail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateActivateAccountEmail indicates an expected call of UpdateActivateAccountEmail.
func (mr *MockDatabaseMockRecorder) UpdateActivateAccountEmail(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateActivateAccountEmail", reflect.TypeOf((*MockDatabase)(nil).UpdateActivateAccountEmail), arg0, arg1)
}

// UpdateSession mocks base method.
func (m *MockDatabase) UpdateSession(arg0 context.Context, arg1 model.UpdateSessionParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSession", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSession indicates an expected call of UpdateSession.
func (mr *MockDatabaseMockRecorder) UpdateSession(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSession", reflect.TypeOf((*MockDatabase)(nil).UpdateSession), arg0, arg1)
}

// UpdateUser mocks base method.
func (m *MockDatabase) UpdateUser(arg0 context.Context, arg1 model.UpdateUserParams) (model.UpdateUserRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUser", arg0, arg1)
	ret0, _ := ret[0].(model.UpdateUserRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockDatabaseMockRecorder) UpdateUser(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockDatabase)(nil).UpdateUser), arg0, arg1)
}
