// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package model

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AlterUserAccountStatus(ctx context.Context, arg AlterUserAccountStatusParams) (User, error)
	CountUsers(ctx context.Context) (int64, error)
	CreateActivateAccountEmail(ctx context.Context, arg CreateActivateAccountEmailParams) (VarifyEmail, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, email string) (int64, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SelectUserByEmail(ctx context.Context, email string) (User, error)
	UpdateActivateAccountEmail(ctx context.Context, secretCode string) (VarifyEmail, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
