// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 1.branches.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createBranch = `-- name: CreateBranch :exec
INSERT INTO branches (
    name,
    code,
    description,
    country,
    region,
    province,
    district,
    city,
    address,
    contact,
    email,
    other,
    is_active,
    subscription
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateBranchParams struct {
	Name         string      `json:"name"`
	Code         string      `json:"code"`
	Description  pgtype.Text `json:"description"`
	Country      string      `json:"country"`
	Region       pgtype.Text `json:"region"`
	Province     pgtype.Text `json:"province"`
	District     pgtype.Text `json:"district"`
	City         pgtype.Text `json:"city"`
	Address      pgtype.Text `json:"address"`
	Contact      pgtype.Text `json:"contact"`
	Email        pgtype.Text `json:"email"`
	Other        []byte      `json:"other"`
	IsActive     bool        `json:"is_active"`
	Subscription string      `json:"subscription"`
}

func (q *Queries) CreateBranch(ctx context.Context, arg CreateBranchParams) error {
	_, err := q.db.Exec(ctx, createBranch,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Country,
		arg.Region,
		arg.Province,
		arg.District,
		arg.City,
		arg.Address,
		arg.Contact,
		arg.Email,
		arg.Other,
		arg.IsActive,
		arg.Subscription,
	)
	return err
}

const deleteBranch = `-- name: DeleteBranch :exec
DELETE FROM branches WHERE id = $1
`

func (q *Queries) DeleteBranch(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteBranch, id)
	return err
}

const getBranchByID = `-- name: GetBranchByID :one
SELECT id, name, code, description, country, region, province, district, city, address, contact, email, other, is_active, subscription, created_at, updated_at FROM branches WHERE id = $1
`

func (q *Queries) GetBranchByID(ctx context.Context, id int64) (Branch, error) {
	row := q.db.QueryRow(ctx, getBranchByID, id)
	var i Branch
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.Country,
		&i.Region,
		&i.Province,
		&i.District,
		&i.City,
		&i.Address,
		&i.Contact,
		&i.Email,
		&i.Other,
		&i.IsActive,
		&i.Subscription,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBranches = `-- name: ListBranches :many
SELECT id, name, code, description, country, region, province, district, city, address, contact, email, other, is_active, subscription, created_at, updated_at FROM branches 
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListBranchesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error) {
	rows, err := q.db.Query(ctx, listBranches, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Branch{}
	for rows.Next() {
		var i Branch
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Country,
			&i.Region,
			&i.Province,
			&i.District,
			&i.City,
			&i.Address,
			&i.Contact,
			&i.Email,
			&i.Other,
			&i.IsActive,
			&i.Subscription,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBranch = `-- name: UpdateBranch :exec
UPDATE branches
SET 
    updated_at = NOW(),
    name = COALESCE($2, name),
    code = COALESCE($3, code),
    description = COALESCE($4, description),
    country = COALESCE($5, country),
    region = COALESCE($6, region),
    province = COALESCE($7, province),
    district = COALESCE($8, district),
    city = COALESCE($9, city),
    address = COALESCE($10, address),
    contact = COALESCE($11, contact),
    email = COALESCE($12, email),
    other = COALESCE($13, other),
    is_active = COALESCE($14, is_active),
    subscription = COALESCE($15, subscription)    
WHERE id = $1
`

type UpdateBranchParams struct {
	ID           int64       `json:"id"`
	Name         pgtype.Text `json:"name"`
	Code         pgtype.Text `json:"code"`
	Description  pgtype.Text `json:"description"`
	Country      pgtype.Text `json:"country"`
	Region       pgtype.Text `json:"region"`
	Province     pgtype.Text `json:"province"`
	District     pgtype.Text `json:"district"`
	City         pgtype.Text `json:"city"`
	Address      pgtype.Text `json:"address"`
	Contact      pgtype.Text `json:"contact"`
	Email        pgtype.Text `json:"email"`
	Other        []byte      `json:"other"`
	IsActive     pgtype.Bool `json:"is_active"`
	Subscription pgtype.Text `json:"subscription"`
}

func (q *Queries) UpdateBranch(ctx context.Context, arg UpdateBranchParams) error {
	_, err := q.db.Exec(ctx, updateBranch,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Country,
		arg.Region,
		arg.Province,
		arg.District,
		arg.City,
		arg.Address,
		arg.Contact,
		arg.Email,
		arg.Other,
		arg.IsActive,
		arg.Subscription,
	)
	return err
}
