// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 1.organizations.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrganization = `-- name: CreateOrganization :exec
INSERT INTO organizations (
    branch,
    name,
    code,
    description,
    is_active,
    contact,
    email,
    country,
    region,
    province,
    district,
    city,
    address,
    other
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
)
`

type CreateOrganizationParams struct {
	Branch      int64       `json:"branch"`
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	Description pgtype.Text `json:"description"`
	IsActive    bool        `json:"is_active"`
	Contact     pgtype.Text `json:"contact"`
	Email       pgtype.Text `json:"email"`
	Country     string      `json:"country"`
	Region      pgtype.Text `json:"region"`
	Province    pgtype.Text `json:"province"`
	District    pgtype.Text `json:"district"`
	City        pgtype.Text `json:"city"`
	Address     pgtype.Text `json:"address"`
	Other       []byte      `json:"other"`
}

func (q *Queries) CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error {
	_, err := q.db.Exec(ctx, createOrganization,
		arg.Branch,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
		arg.Contact,
		arg.Email,
		arg.Country,
		arg.Region,
		arg.Province,
		arg.District,
		arg.City,
		arg.Address,
		arg.Other,
	)
	return err
}

const deleteOrganization = `-- name: DeleteOrganization :exec
DELETE FROM organizations WHERE id = $1
`

func (q *Queries) DeleteOrganization(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteOrganization, id)
	return err
}

const getOrganizationByID = `-- name: GetOrganizationByID :one
SELECT id, branch, name, code, description, is_active, contact, email, country, region, province, district, city, address, other, created_at, updated_at FROM organizations WHERE id = $1
`

func (q *Queries) GetOrganizationByID(ctx context.Context, id int64) (Organization, error) {
	row := q.db.QueryRow(ctx, getOrganizationByID, id)
	var i Organization
	err := row.Scan(
		&i.ID,
		&i.Branch,
		&i.Name,
		&i.Code,
		&i.Description,
		&i.IsActive,
		&i.Contact,
		&i.Email,
		&i.Country,
		&i.Region,
		&i.Province,
		&i.District,
		&i.City,
		&i.Address,
		&i.Other,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrganizations = `-- name: ListOrganizations :many
SELECT id, branch, name, code, description, is_active, contact, email, country, region, province, district, city, address, other, created_at, updated_at FROM organizations 
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListOrganizationsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error) {
	rows, err := q.db.Query(ctx, listOrganizations, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Organization{}
	for rows.Next() {
		var i Organization
		if err := rows.Scan(
			&i.ID,
			&i.Branch,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.IsActive,
			&i.Contact,
			&i.Email,
			&i.Country,
			&i.Region,
			&i.Province,
			&i.District,
			&i.City,
			&i.Address,
			&i.Other,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrganization = `-- name: UpdateOrganization :exec
UPDATE organizations
SET 
    updated_at = NOW(),
    branch = COALESCE($2, branch),
    name = COALESCE($3, name),
    code = COALESCE($4, code),
    description = COALESCE($5, description),
    is_active = COALESCE($6, is_active),
    contact = COALESCE($7, contact),
    email = COALESCE($8, email),
    country = COALESCE($9, country),
    region = COALESCE($10, region),
    province = COALESCE($11, province),
    district = COALESCE($12, district),
    city = COALESCE($13, city),
    address = COALESCE($14, address),
    other = COALESCE($15, other)

WHERE id = $1
`

type UpdateOrganizationParams struct {
	ID          int64       `json:"id"`
	Branch      pgtype.Int8 `json:"branch"`
	Name        pgtype.Text `json:"name"`
	Code        pgtype.Text `json:"code"`
	Description pgtype.Text `json:"description"`
	IsActive    pgtype.Bool `json:"is_active"`
	Contact     pgtype.Text `json:"contact"`
	Email       pgtype.Text `json:"email"`
	Country     pgtype.Text `json:"country"`
	Region      pgtype.Text `json:"region"`
	Province    pgtype.Text `json:"province"`
	District    pgtype.Text `json:"district"`
	City        pgtype.Text `json:"city"`
	Address     pgtype.Text `json:"address"`
	Other       []byte      `json:"other"`
}

func (q *Queries) UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error {
	_, err := q.db.Exec(ctx, updateOrganization,
		arg.ID,
		arg.Branch,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.IsActive,
		arg.Contact,
		arg.Email,
		arg.Country,
		arg.Region,
		arg.Province,
		arg.District,
		arg.City,
		arg.Address,
		arg.Other,
	)
	return err
}
