// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 2.branch_org_users.sql

package model

import (
	"context"
)

const createBranchUser = `-- name: CreateBranchUser :exec
INSERT INTO branch_users (
    branch,
    user_id
) VALUES ( $1, $2 )
`

type CreateBranchUserParams struct {
	Branch int64  `json:"branch"`
	UserID string `json:"user_id"`
}

func (q *Queries) CreateBranchUser(ctx context.Context, arg CreateBranchUserParams) error {
	_, err := q.db.Exec(ctx, createBranchUser, arg.Branch, arg.UserID)
	return err
}

const createOrganizationUser = `-- name: CreateOrganizationUser :exec
INSERT INTO organization_users (
    organization,
    user_id
) VALUES ( $1, $2 )
`

type CreateOrganizationUserParams struct {
	Organization int64  `json:"organization"`
	UserID       string `json:"user_id"`
}

func (q *Queries) CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) error {
	_, err := q.db.Exec(ctx, createOrganizationUser, arg.Organization, arg.UserID)
	return err
}

const deleteBranchUser = `-- name: DeleteBranchUser :exec
DELETE FROM branch_users 
WHERE branch = $1 AND user_id = $2
`

type DeleteBranchUserParams struct {
	Branch int64  `json:"branch"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteBranchUser(ctx context.Context, arg DeleteBranchUserParams) error {
	_, err := q.db.Exec(ctx, deleteBranchUser, arg.Branch, arg.UserID)
	return err
}

const deleteOrganizationUser = `-- name: DeleteOrganizationUser :exec
DELETE FROM organization_users
WHERE organization = $1 AND user_id = $2
`

type DeleteOrganizationUserParams struct {
	Organization int64  `json:"organization"`
	UserID       string `json:"user_id"`
}

func (q *Queries) DeleteOrganizationUser(ctx context.Context, arg DeleteOrganizationUserParams) error {
	_, err := q.db.Exec(ctx, deleteOrganizationUser, arg.Organization, arg.UserID)
	return err
}
