// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 2.sessions.sql

package model

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :exec
INSERT INTO
  sessions (
    id,
    user_id,
    refresh_token,
    user_agent,
    client_ip,
    platform,
    device,
    expiry
  )
VALUES
  ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	ID           uuid.UUID   `json:"id"`
	UserID       string      `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	Platform     pgtype.Text `json:"platform"`
	Device       pgtype.Text `json:"device"`
	Expiry       time.Time   `json:"expiry"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.RefreshToken,
		arg.UserAgent,
		arg.ClientIp,
		arg.Platform,
		arg.Device,
		arg.Expiry,
	)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions
WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT  id, user_id, refresh_token, user_agent, client_ip, description, other, platform, device, is_blocked, expiry, created_at
FROM  sessions
WHERE  id = $1
`

func (q *Queries) GetSession(ctx context.Context, id uuid.UUID) (Session, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshToken,
		&i.UserAgent,
		&i.ClientIp,
		&i.Description,
		&i.Other,
		&i.Platform,
		&i.Device,
		&i.IsBlocked,
		&i.Expiry,
		&i.CreatedAt,
	)
	return i, err
}

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions
SET
  refresh_token = COALESCE($2),
  expiry = COALESCE($3),
  is_blocked = COALESCE($4)
WHERE
  id = $1
`

type UpdateSessionParams struct {
	ID           uuid.UUID          `json:"id"`
	RefreshToken pgtype.Text        `json:"refresh_token"`
	Expiry       pgtype.Timestamptz `json:"expiry"`
	IsBlocked    pgtype.Bool        `json:"is_blocked"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.RefreshToken,
		arg.Expiry,
		arg.IsBlocked,
	)
	return err
}
