// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 2.users.sql

package model

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (
    id,
    first_name,
    middle_name,
    last_name,
    other_name,
    email,
    contact,
    password,
    role,
    type
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type CreateUserParams struct {
	ID         string      `json:"id"`
	FirstName  string      `json:"first_name"`
	MiddleName pgtype.Text `json:"middle_name"`
	LastName   string      `json:"last_name"`
	OtherName  pgtype.Text `json:"other_name"`
	Email      string      `json:"email"`
	Contact    string      `json:"contact"`
	Password   string      `json:"password"`
	Role       string      `json:"role"`
	Type       string      `json:"type"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.OtherName,
		arg.Email,
		arg.Contact,
		arg.Password,
		arg.Role,
		arg.Type,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :one
DELETE FROM users
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteUser(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, deleteUser, id)
	err := row.Scan(&id)
	return id, err
}

const getUser = `-- name: GetUser :one
SELECT id, first_name, middle_name, last_name, other_name, email, contact, password, is_active, is_locked, mfa_enabled, failed_attempts, notes, is_contact_verified, is_email_verified, last_security_check, last_password_change, last_login, accepted_terms, role, type, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OtherName,
		&i.Email,
		&i.Contact,
		&i.Password,
		&i.IsActive,
		&i.IsLocked,
		&i.MfaEnabled,
		&i.FailedAttempts,
		&i.Notes,
		&i.IsContactVerified,
		&i.IsEmailVerified,
		&i.LastSecurityCheck,
		&i.LastPasswordChange,
		&i.LastLogin,
		&i.AcceptedTerms,
		&i.Role,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT 
  id, first_name, middle_name, last_name, other_name, email, contact, 
  role, type, is_active, is_locked, mfa_enabled, failed_attempts, 
  is_email_verified, is_contact_verified, created_at, updated_at
FROM users
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListUsersRow struct {
	ID                string             `json:"id"`
	FirstName         string             `json:"first_name"`
	MiddleName        pgtype.Text        `json:"middle_name"`
	LastName          string             `json:"last_name"`
	OtherName         pgtype.Text        `json:"other_name"`
	Email             string             `json:"email"`
	Contact           string             `json:"contact"`
	Role              string             `json:"role"`
	Type              string             `json:"type"`
	IsActive          bool               `json:"is_active"`
	IsLocked          bool               `json:"is_locked"`
	MfaEnabled        bool               `json:"mfa_enabled"`
	FailedAttempts    int32              `json:"failed_attempts"`
	IsEmailVerified   bool               `json:"is_email_verified"`
	IsContactVerified bool               `json:"is_contact_verified"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUsersRow{}
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.MiddleName,
			&i.LastName,
			&i.OtherName,
			&i.Email,
			&i.Contact,
			&i.Role,
			&i.Type,
			&i.IsActive,
			&i.IsLocked,
			&i.MfaEnabled,
			&i.FailedAttempts,
			&i.IsEmailVerified,
			&i.IsContactVerified,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const selectUserByContact = `-- name: SelectUserByContact :one
SELECT id, first_name, middle_name, last_name, other_name, email, contact, password, is_active, is_locked, mfa_enabled, failed_attempts, notes, is_contact_verified, is_email_verified, last_security_check, last_password_change, last_login, accepted_terms, role, type, created_at, updated_at FROM users
WHERE contact = $1
LIMIT 1
`

func (q *Queries) SelectUserByContact(ctx context.Context, contact string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByContact, contact)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OtherName,
		&i.Email,
		&i.Contact,
		&i.Password,
		&i.IsActive,
		&i.IsLocked,
		&i.MfaEnabled,
		&i.FailedAttempts,
		&i.Notes,
		&i.IsContactVerified,
		&i.IsEmailVerified,
		&i.LastSecurityCheck,
		&i.LastPasswordChange,
		&i.LastLogin,
		&i.AcceptedTerms,
		&i.Role,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectUserByEmail = `-- name: SelectUserByEmail :one
SELECT id, first_name, middle_name, last_name, other_name, email, contact, password, is_active, is_locked, mfa_enabled, failed_attempts, notes, is_contact_verified, is_email_verified, last_security_check, last_password_change, last_login, accepted_terms, role, type, created_at, updated_at FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) SelectUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, selectUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.MiddleName,
		&i.LastName,
		&i.OtherName,
		&i.Email,
		&i.Contact,
		&i.Password,
		&i.IsActive,
		&i.IsLocked,
		&i.MfaEnabled,
		&i.FailedAttempts,
		&i.Notes,
		&i.IsContactVerified,
		&i.IsEmailVerified,
		&i.LastSecurityCheck,
		&i.LastPasswordChange,
		&i.LastLogin,
		&i.AcceptedTerms,
		&i.Role,
		&i.Type,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserContactInfo = `-- name: UpdateUserContactInfo :exec
UPDATE users
SET 
  updated_at = NOW(),
  email = COALESCE($2, email),
  contact = COALESCE($3, contact),
  is_email_verified = COALESCE($4, is_email_verified),
  is_contact_verified = COALESCE($5, is_contact_verified)
WHERE id = $1
`

type UpdateUserContactInfoParams struct {
	ID                string      `json:"id"`
	Email             pgtype.Text `json:"email"`
	Contact           pgtype.Text `json:"contact"`
	IsEmailVerified   pgtype.Bool `json:"is_email_verified"`
	IsContactVerified pgtype.Bool `json:"is_contact_verified"`
}

func (q *Queries) UpdateUserContactInfo(ctx context.Context, arg UpdateUserContactInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserContactInfo,
		arg.ID,
		arg.Email,
		arg.Contact,
		arg.IsEmailVerified,
		arg.IsContactVerified,
	)
	return err
}

const updateUserPersonalInfo = `-- name: UpdateUserPersonalInfo :exec
UPDATE users
SET 
  updated_at = NOW(),
  first_name = COALESCE($2, first_name),
  middle_name = COALESCE($3, middle_name),
  last_name = COALESCE($4, last_name),
  other_name = COALESCE($5, other_name)
WHERE id = $1
`

type UpdateUserPersonalInfoParams struct {
	ID         string      `json:"id"`
	FirstName  pgtype.Text `json:"first_name"`
	MiddleName pgtype.Text `json:"middle_name"`
	LastName   pgtype.Text `json:"last_name"`
	OtherName  pgtype.Text `json:"other_name"`
}

func (q *Queries) UpdateUserPersonalInfo(ctx context.Context, arg UpdateUserPersonalInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserPersonalInfo,
		arg.ID,
		arg.FirstName,
		arg.MiddleName,
		arg.LastName,
		arg.OtherName,
	)
	return err
}

const updateUserRoleAndType = `-- name: UpdateUserRoleAndType :exec
UPDATE users
SET 
  updated_at = NOW(),
  role = COALESCE($2, role),
  type = COALESCE($3, type)
WHERE id = $1
`

type UpdateUserRoleAndTypeParams struct {
	ID   string      `json:"id"`
	Role pgtype.Text `json:"role"`
	Type pgtype.Text `json:"type"`
}

func (q *Queries) UpdateUserRoleAndType(ctx context.Context, arg UpdateUserRoleAndTypeParams) error {
	_, err := q.db.Exec(ctx, updateUserRoleAndType, arg.ID, arg.Role, arg.Type)
	return err
}

const updateUserSecurityInfo = `-- name: UpdateUserSecurityInfo :exec
UPDATE users
SET 
  updated_at = NOW(),
  password = COALESCE($2, password),
  is_locked = COALESCE($3, is_locked),
  mfa_enabled = COALESCE($4, mfa_enabled),
  failed_attempts = COALESCE($5, failed_attempts),
  last_password_change = COALESCE($6, last_password_change),
  last_security_check = COALESCE($7, last_security_check)
WHERE id = $1
`

type UpdateUserSecurityInfoParams struct {
	ID                 string             `json:"id"`
	Password           pgtype.Text        `json:"password"`
	IsLocked           pgtype.Bool        `json:"is_locked"`
	MfaEnabled         pgtype.Bool        `json:"mfa_enabled"`
	FailedAttempts     pgtype.Int4        `json:"failed_attempts"`
	LastPasswordChange pgtype.Timestamptz `json:"last_password_change"`
	LastSecurityCheck  pgtype.Timestamptz `json:"last_security_check"`
}

func (q *Queries) UpdateUserSecurityInfo(ctx context.Context, arg UpdateUserSecurityInfoParams) error {
	_, err := q.db.Exec(ctx, updateUserSecurityInfo,
		arg.ID,
		arg.Password,
		arg.IsLocked,
		arg.MfaEnabled,
		arg.FailedAttempts,
		arg.LastPasswordChange,
		arg.LastSecurityCheck,
	)
	return err
}

const updateUserStatus = `-- name: UpdateUserStatus :exec
UPDATE users
SET 
  updated_at = NOW(),
  is_active = COALESCE($2, is_active),
  accepted_terms = COALESCE($3, accepted_terms)
WHERE id = $1
`

type UpdateUserStatusParams struct {
	ID            string      `json:"id"`
	IsActive      pgtype.Bool `json:"is_active"`
	AcceptedTerms pgtype.Bool `json:"accepted_terms"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error {
	_, err := q.db.Exec(ctx, updateUserStatus, arg.ID, arg.IsActive, arg.AcceptedTerms)
	return err
}
