// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 2.verifications.sql

package model

import (
	"context"
)

const createVerification = `-- name: CreateVerification :exec
INSERT INTO verifications (
    expiry,
    user_id,
    otp,
    channel,
    purpose
) VALUES (
    NOW() + INTERVAL '10 minutes', $1, $2, $3, $4
)
`

type CreateVerificationParams struct {
	UserID  string `json:"user_id"`
	Otp     string `json:"otp"`
	Channel string `json:"channel"`
	Purpose string `json:"purpose"`
}

func (q *Queries) CreateVerification(ctx context.Context, arg CreateVerificationParams) error {
	_, err := q.db.Exec(ctx, createVerification,
		arg.UserID,
		arg.Otp,
		arg.Channel,
		arg.Purpose,
	)
	return err
}

const getVerificationUser = `-- name: GetVerificationUser :one
 SELECT user_id FROM verifications 
 WHERE otp = $1
    AND is_used = FALSE
    AND expiry > NOW()
 LIMIT 1
`

func (q *Queries) GetVerificationUser(ctx context.Context, otp string) (string, error) {
	row := q.db.QueryRow(ctx, getVerificationUser, otp)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const updateVerification = `-- name: UpdateVerification :exec
UPDATE verifications
SET
    is_used = TRUE
WHERE otp = $1
    AND is_used = FALSE
    AND expiry > NOW()
`

func (q *Queries) UpdateVerification(ctx context.Context, otp string) error {
	_, err := q.db.Exec(ctx, updateVerification, otp)
	return err
}
