// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 3.permissions.sql

package model

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPermission = `-- name: CreatePermission :exec
INSERT INTO permissions (
    name,
    code,
    description,
    resource,
    privacy
) VALUES ( $1, $2, $3, $4, $5
)
`

type CreatePermissionParams struct {
	Name        string      `json:"name"`
	Code        string      `json:"code"`
	Description pgtype.Text `json:"description"`
	Resource    string      `json:"resource"`
	Privacy     string      `json:"privacy"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) error {
	_, err := q.db.Exec(ctx, createPermission,
		arg.Name,
		arg.Code,
		arg.Description,
		arg.Resource,
		arg.Privacy,
	)
	return err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM permissions
WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermission = `-- name: GetPermission :many
SELECT id, name, code, description, resource, privacy, created_at, updated_at
FROM permissions
WHERE privacy IN ($1)
`

func (q *Queries) GetPermission(ctx context.Context, privacy []string) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getPermission, privacy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Resource,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT 
  id, name, code, description, resource, privacy, created_at, updated_at, COUNT(*) OVER () AS count
FROM permissions 
WHERE privacy IN ($3)
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListPermissionsParams struct {
	Limit   int32    `json:"limit"`
	Offset  int32    `json:"offset"`
	Privacy []string `json:"privacy"`
}

type ListPermissionsRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	Resource    string             `json:"resource"`
	Privacy     string             `json:"privacy"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Count       int64              `json:"count"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Limit, arg.Offset, arg.Privacy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPermissionsRow{}
	for rows.Next() {
		var i ListPermissionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Resource,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :exec
UPDATE permissions
SET 
    updated = NOW(),
    name = COALESCE($2, name),
    code = COALESCE($3, code),
    privacy = COALESCE($4, privacy),
    resource = COALESCE($5, resource),
    description = COALESCE($6, description)
WHERE
id = $1
`

type UpdatePermissionParams struct {
	ID          int64       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Code        pgtype.Text `json:"code"`
	Privacy     pgtype.Text `json:"privacy"`
	Resource    pgtype.Text `json:"resource"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error {
	_, err := q.db.Exec(ctx, updatePermission,
		arg.ID,
		arg.Name,
		arg.Code,
		arg.Privacy,
		arg.Resource,
		arg.Description,
	)
	return err
}
