// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 3.roles .sql

package model

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRole = `-- name: CreateRole :exec
INSERT INTO roles (
  name,
  reference,
  scope,
  tag,
  description    
) VALUES (
  $1, $2, $3, $4, $5
)
`

type CreateRoleParams struct {
	Name        string `json:"name"`
	Reference   int64  `json:"reference"`
	Scope       string `json:"scope"`
	Tag         string `json:"tag"`
	Description string `json:"description"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) error {
	_, err := q.db.Exec(ctx, createRole,
		arg.Name,
		arg.Reference,
		arg.Scope,
		arg.Tag,
		arg.Description,
	)
	return err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM roles
WHERE id = $1
  AND (reference = $2)
`

type DeleteRoleParams struct {
	ID        int64 `json:"id"`
	Reference int64 `json:"reference"`
}

func (q *Queries) DeleteRole(ctx context.Context, arg DeleteRoleParams) error {
	_, err := q.db.Exec(ctx, deleteRole, arg.ID, arg.Reference)
	return err
}

const getRoles = `-- name: GetRoles :many
SELECT id, name, tag, reference, scope
FROM roles
WHERE ($1 IS NULL OR reference = $1)
`

type GetRolesRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Tag       string `json:"tag"`
	Reference int64  `json:"reference"`
	Scope     string `json:"scope"`
}

func (q *Queries) GetRoles(ctx context.Context, reference interface{}) ([]GetRolesRow, error) {
	rows, err := q.db.Query(ctx, getRoles, reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetRolesRow{}
	for rows.Next() {
		var i GetRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Tag,
			&i.Reference,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRoles = `-- name: ListAllRoles :many
SELECT id, name, reference, scope, description, tag, created_at, updated_at, CAST(COUNT(*) OVER () AS SIGNED) AS total_count
FROM roles
WHERE reference IS NULL 
ORDER BY id DESC
LIMIT $1 OFFSET $2
`

type ListAllRolesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAllRolesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Reference   int64              `json:"reference"`
	Scope       string             `json:"scope"`
	Description string             `json:"description"`
	Tag         string             `json:"tag"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TotalCount  interface{}        `json:"total_count"`
}

func (q *Queries) ListAllRoles(ctx context.Context, arg ListAllRolesParams) ([]ListAllRolesRow, error) {
	rows, err := q.db.Query(ctx, listAllRoles, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllRolesRow{}
	for rows.Next() {
		var i ListAllRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Reference,
			&i.Scope,
			&i.Description,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, name, reference, scope, description, tag, created_at, updated_at, CAST(COUNT(*) OVER () AS SIGNED) AS total_count
FROM roles
WHERE reference = $1
ORDER BY id DESC
LIMIT $2 OFFSET $3
`

type ListRolesParams struct {
	Reference int64 `json:"reference"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

type ListRolesRow struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Reference   int64              `json:"reference"`
	Scope       string             `json:"scope"`
	Description string             `json:"description"`
	Tag         string             `json:"tag"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TotalCount  interface{}        `json:"total_count"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Reference, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListRolesRow{}
	for rows.Next() {
		var i ListRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Reference,
			&i.Scope,
			&i.Description,
			&i.Tag,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :exec
UPDATE roles
SET 
    updated = NOW(),
    name = COALESCE($2, name),
    tag = COALESCE($3, tag),
    reference = COALESCE($4, reference),
    description = COALESCE($5, description)
WHERE id = $1
`

type UpdateRoleParams struct {
	ID          int64       `json:"id"`
	Name        pgtype.Text `json:"name"`
	Tag         pgtype.Text `json:"tag"`
	Reference   pgtype.Int8 `json:"reference"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) error {
	_, err := q.db.Exec(ctx, updateRole,
		arg.ID,
		arg.Name,
		arg.Tag,
		arg.Reference,
		arg.Description,
	)
	return err
}
