// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 3.role_permissions.sql

package model

import (
	"context"
)

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO privileges (
    role,
    permission    
) VALUES ($1, $2)
`

type CreateRolePermissionParams struct {
	Role       int64 `json:"role"`
	Permission int64 `json:"permission"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createRolePermission, arg.Role, arg.Permission)
	return err
}

const deleteRolePermission = `-- name: DeleteRolePermission :exec
DELETE FROM privileges
WHERE permission = $1 AND role = $2
`

type DeleteRolePermissionParams struct {
	Permission int64 `json:"permission"`
	Role       int64 `json:"role"`
}

func (q *Queries) DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error {
	_, err := q.db.Exec(ctx, deleteRolePermission, arg.Permission, arg.Role)
	return err
}

const getRole = `-- name: GetRole :one
SELECT  r.id, r.name, r.reference, r.scope, r.description, r.tag, r.created_at, r.updated_at
FROM roles r
WHERE (r.reference = $1 OR ($1 IS NULL AND r.reference IS NULL))
  AND r.id = $2
`

type GetRoleParams struct {
	Reference int64 `json:"reference"`
	ID        int64 `json:"id"`
}

func (q *Queries) GetRole(ctx context.Context, arg GetRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, arg.Reference, arg.ID)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Reference,
		&i.Scope,
		&i.Description,
		&i.Tag,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRolePermission = `-- name: GetRolePermission :many
SELECT permission FROM privileges
WHERE  role = $1
`

func (q *Queries) GetRolePermission(ctx context.Context, role int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, getRolePermission, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var permission int64
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissions = `-- name: GetRolePermissions :many
SELECT p.id, p.name, p.code, p.description, p.resource, p.privacy, p.created_at, p.updated_at
FROM permissions p
JOIN privileges rp ON rp.permission = p.id
WHERE rp.role = $1
`

func (q *Queries) GetRolePermissions(ctx context.Context, role int64) ([]Permission, error) {
	rows, err := q.db.Query(ctx, getRolePermissions, role)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Permission{}
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Description,
			&i.Resource,
			&i.Privacy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
