// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: 3.user_roles.sql

package model

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assingnNamedRoleToUser = `-- name: AssingnNamedRoleToUser :exec
INSERT INTO authorities (user_id, role, reference)
SELECT $1, id, $2
FROM roles
WHERE name = $1 AND reference IS NULL
`

type AssingnNamedRoleToUserParams struct {
	UserID    string `json:"user_id"`
	Reference int64  `json:"reference"`
}

func (q *Queries) AssingnNamedRoleToUser(ctx context.Context, arg AssingnNamedRoleToUserParams) error {
	_, err := q.db.Exec(ctx, assingnNamedRoleToUser, arg.UserID, arg.Reference)
	return err
}

const createUserRole = `-- name: CreateUserRole :exec
INSERT INTO authorities (
    user_id,
    role,
    reference
) VALUES ($1, $2, $3)
`

type CreateUserRoleParams struct {
	UserID    string `json:"user_id"`
	Role      int64  `json:"role"`
	Reference int64  `json:"reference"`
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error {
	_, err := q.db.Exec(ctx, createUserRole, arg.UserID, arg.Role, arg.Reference)
	return err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM authorities
WHERE role = $1 AND user_id = $2 AND reference = COALESCE($3, reference)
`

type DeleteUserRoleParams struct {
	Role      int64       `json:"role"`
	UserID    string      `json:"user_id"`
	Reference pgtype.Int8 `json:"reference"`
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.Exec(ctx, deleteUserRole, arg.Role, arg.UserID, arg.Reference)
	return err
}

const getUserRoles = `-- name: GetUserRoles :many
SELECT r.name, r.reference
FROM authorities ur
JOIN roles r ON ur.role = r.id
WHERE ur.user_id = $1 AND r.reference = COALESCE($2, r.reference)
`

type GetUserRolesParams struct {
	UserID    string      `json:"user_id"`
	Reference pgtype.Int8 `json:"reference"`
}

type GetUserRolesRow struct {
	Name      string `json:"name"`
	Reference int64  `json:"reference"`
}

func (q *Queries) GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]GetUserRolesRow, error) {
	rows, err := q.db.Query(ctx, getUserRoles, arg.UserID, arg.Reference)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesRow{}
	for rows.Next() {
		var i GetUserRolesRow
		if err := rows.Scan(&i.Name, &i.Reference); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRolesByBranch = `-- name: GetUserRolesByBranch :many
SELECT 
  COALESCE(ur.reference, 0) AS reference, 
  r.name AS role,
  p.code AS permission
FROM authorities ur
JOIN roles r ON ur.role = r.id
JOIN privileges rp ON rp.role = r.id
JOIN permissions p ON p.id = rp.permission
WHERE ur.user_id = $1
ORDER BY ur.reference, r.name
`

type GetUserRolesByBranchRow struct {
	Reference  int64  `json:"reference"`
	Role       string `json:"role"`
	Permission string `json:"permission"`
}

func (q *Queries) GetUserRolesByBranch(ctx context.Context, userID string) ([]GetUserRolesByBranchRow, error) {
	rows, err := q.db.Query(ctx, getUserRolesByBranch, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUserRolesByBranchRow{}
	for rows.Next() {
		var i GetUserRolesByBranchRow
		if err := rows.Scan(&i.Reference, &i.Role, &i.Permission); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
