// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Authority struct {
	UserID    string    `json:"user_id"`
	Reference int64     `json:"reference"`
	Scope     string    `json:"scope"`
	Role      int64     `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}

type Branch struct {
	ID           int64              `json:"id"`
	Name         string             `json:"name"`
	Code         string             `json:"code"`
	Description  pgtype.Text        `json:"description"`
	Country      string             `json:"country"`
	Region       pgtype.Text        `json:"region"`
	Province     pgtype.Text        `json:"province"`
	District     pgtype.Text        `json:"district"`
	City         pgtype.Text        `json:"city"`
	Address      pgtype.Text        `json:"address"`
	Contact      pgtype.Text        `json:"contact"`
	Email        pgtype.Text        `json:"email"`
	Other        []byte             `json:"other"`
	IsActive     bool               `json:"is_active"`
	Subscription string             `json:"subscription"`
	CreatedAt    time.Time          `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type BranchUser struct {
	Branch int64  `json:"branch"`
	UserID string `json:"user_id"`
}

type Organization struct {
	ID          int64              `json:"id"`
	Branch      int64              `json:"branch"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	IsActive    bool               `json:"is_active"`
	Contact     pgtype.Text        `json:"contact"`
	Email       pgtype.Text        `json:"email"`
	Country     string             `json:"country"`
	Region      pgtype.Text        `json:"region"`
	Province    pgtype.Text        `json:"province"`
	District    pgtype.Text        `json:"district"`
	City        pgtype.Text        `json:"city"`
	Address     pgtype.Text        `json:"address"`
	Other       []byte             `json:"other"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type OrganizationUser struct {
	Organization int64  `json:"organization"`
	UserID       string `json:"user_id"`
}

type Permission struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Code        string             `json:"code"`
	Description pgtype.Text        `json:"description"`
	Resource    string             `json:"resource"`
	Privacy     string             `json:"privacy"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Privilege struct {
	Role       int64     `json:"role"`
	Permission int64     `json:"permission"`
	CreatedAt  time.Time `json:"created_at"`
}

type Role struct {
	ID          int64              `json:"id"`
	Name        string             `json:"name"`
	Reference   int64              `json:"reference"`
	Scope       string             `json:"scope"`
	Description string             `json:"description"`
	Tag         string             `json:"tag"`
	CreatedAt   time.Time          `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID           uuid.UUID   `json:"id"`
	UserID       string      `json:"user_id"`
	RefreshToken string      `json:"refresh_token"`
	UserAgent    string      `json:"user_agent"`
	ClientIp     string      `json:"client_ip"`
	Description  pgtype.Text `json:"description"`
	Other        []byte      `json:"other"`
	Platform     pgtype.Text `json:"platform"`
	Device       pgtype.Text `json:"device"`
	IsBlocked    bool        `json:"is_blocked"`
	Expiry       time.Time   `json:"expiry"`
	CreatedAt    time.Time   `json:"created_at"`
}

type User struct {
	ID                 string             `json:"id"`
	FirstName          string             `json:"first_name"`
	MiddleName         pgtype.Text        `json:"middle_name"`
	LastName           string             `json:"last_name"`
	OtherName          pgtype.Text        `json:"other_name"`
	Email              string             `json:"email"`
	Contact            string             `json:"contact"`
	Password           string             `json:"password"`
	IsActive           bool               `json:"is_active"`
	IsLocked           bool               `json:"is_locked"`
	MfaEnabled         bool               `json:"mfa_enabled"`
	FailedAttempts     int32              `json:"failed_attempts"`
	Notes              pgtype.Text        `json:"notes"`
	IsContactVerified  bool               `json:"is_contact_verified"`
	IsEmailVerified    bool               `json:"is_email_verified"`
	LastSecurityCheck  pgtype.Timestamptz `json:"last_security_check"`
	LastPasswordChange pgtype.Timestamptz `json:"last_password_change"`
	LastLogin          pgtype.Timestamptz `json:"last_login"`
	AcceptedTerms      bool               `json:"accepted_terms"`
	Role               string             `json:"role"`
	Type               string             `json:"type"`
	CreatedAt          time.Time          `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

type UserProfile struct {
	ID                string             `json:"id"`
	Title             pgtype.Text        `json:"title"`
	Gender            string             `json:"gender"`
	Avatar            pgtype.Text        `json:"avatar"`
	DateOfBirth       pgtype.Date        `json:"date_of_birth"`
	Country           string             `json:"country"`
	IdentityDocument  string             `json:"identity_document"`
	IdentityNumber    string             `json:"identity_number"`
	IDFront           pgtype.Text        `json:"id_front"`
	IDBack            pgtype.Text        `json:"id_back"`
	NetworkProvider   pgtype.Text        `json:"network_provider"`
	AcceptedMarketing bool               `json:"accepted_marketing"`
	Bio               pgtype.Text        `json:"bio"`
	Other             []byte             `json:"other"`
	Region            pgtype.Text        `json:"region"`
	Province          pgtype.Text        `json:"province"`
	District          pgtype.Text        `json:"district"`
	City              pgtype.Text        `json:"city"`
	Address           pgtype.Text        `json:"address"`
	Latitude          interface{}        `json:"latitude"`
	Longitude         interface{}        `json:"longitude"`
	Signature         pgtype.Text        `json:"signature"`
	CreatedAt         time.Time          `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Verification struct {
	ID        int64     `json:"id"`
	UserID    string    `json:"user_id"`
	Otp       string    `json:"otp"`
	Purpose   string    `json:"purpose"`
	Channel   string    `json:"channel"`
	IsUsed    bool      `json:"is_used"`
	Expiry    time.Time `json:"expiry"`
	CreatedAt time.Time `json:"created_at"`
}
