// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package model

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AssingnNamedRoleToUser(ctx context.Context, arg AssingnNamedRoleToUserParams) error
	CountUsers(ctx context.Context) (int64, error)
	CreateBranch(ctx context.Context, arg CreateBranchParams) error
	CreateBranchUser(ctx context.Context, arg CreateBranchUserParams) error
	CreateOrganization(ctx context.Context, arg CreateOrganizationParams) error
	CreateOrganizationUser(ctx context.Context, arg CreateOrganizationUserParams) error
	CreatePermission(ctx context.Context, arg CreatePermissionParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) error
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) error
	CreateVerification(ctx context.Context, arg CreateVerificationParams) error
	DeleteBranch(ctx context.Context, id int64) error
	DeleteBranchUser(ctx context.Context, arg DeleteBranchUserParams) error
	DeleteOrganization(ctx context.Context, id int64) error
	DeleteOrganizationUser(ctx context.Context, arg DeleteOrganizationUserParams) error
	DeletePermission(ctx context.Context, id int64) error
	DeleteRole(ctx context.Context, arg DeleteRoleParams) error
	DeleteRolePermission(ctx context.Context, arg DeleteRolePermissionParams) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id string) (string, error)
	DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error
	GetBranchByID(ctx context.Context, id int64) (Branch, error)
	GetOrganizationByID(ctx context.Context, id int64) (Organization, error)
	GetPermission(ctx context.Context, privacy []string) ([]Permission, error)
	GetRole(ctx context.Context, arg GetRoleParams) (Role, error)
	GetRolePermission(ctx context.Context, role int64) ([]int64, error)
	GetRolePermissions(ctx context.Context, role int64) ([]Permission, error)
	GetRoles(ctx context.Context, reference interface{}) ([]GetRolesRow, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, id string) (User, error)
	GetUserRoles(ctx context.Context, arg GetUserRolesParams) ([]GetUserRolesRow, error)
	GetUserRolesByBranch(ctx context.Context, userID string) ([]GetUserRolesByBranchRow, error)
	GetVerificationUser(ctx context.Context, otp string) (string, error)
	ListAllRoles(ctx context.Context, arg ListAllRolesParams) ([]ListAllRolesRow, error)
	ListBranches(ctx context.Context, arg ListBranchesParams) ([]Branch, error)
	ListOrganizations(ctx context.Context, arg ListOrganizationsParams) ([]Organization, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]ListPermissionsRow, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]ListRolesRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	SelectUserByContact(ctx context.Context, contact string) (User, error)
	SelectUserByEmail(ctx context.Context, email string) (User, error)
	UpdateBranch(ctx context.Context, arg UpdateBranchParams) error
	UpdateOrganization(ctx context.Context, arg UpdateOrganizationParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateSession(ctx context.Context, arg UpdateSessionParams) error
	UpdateUserContactInfo(ctx context.Context, arg UpdateUserContactInfoParams) error
	UpdateUserPersonalInfo(ctx context.Context, arg UpdateUserPersonalInfoParams) error
	UpdateUserRoleAndType(ctx context.Context, arg UpdateUserRoleAndTypeParams) error
	UpdateUserSecurityInfo(ctx context.Context, arg UpdateUserSecurityInfoParams) error
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) error
	UpdateVerification(ctx context.Context, otp string) error
}

var _ Querier = (*Queries)(nil)
